baseURL = "https://rodenas.org/"
languageCode = "en-us"
removePathAccents = true
googleAnalytics = "UA-88748-1"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[privacy]
  [privacy.disqus]
    disable = true
  [privacy.googleAnalytics]
    disable = false
    anonymizeIP = false
    respectDoNotTrack = true
    useSessionStorage = false
  [privacy.instagram]
    disable = true
  [privacy.twitter]
    disable = false
    enableDNT = false
    simple = false
  [privacy.vimeo]
    disable = false
    simple = false
  [privacy.youtube]
    disable = false
    privacyEnhanced = true

[params]
  verifyV1 = "gLQiua3aPM/F1rGBlT0VfVkAM69VOtdt/ZhLbcCIljs="

[permalinks]
  btags = "/blog/tags/:slug/"
  bcategories = "/blog/categories/:slug/"
  b2011 = "/blog/2011/:slug/"
  b2010 = "/blog/2010/:slug/"
  b2009 = "/blog/2009/:slug/"
  b2008 = "/blog/2008/:slug/"
  b2007 = "/blog/2007/:slug/"
  b2006 = "/blog/2006/:slug/"
  fbtags = "/ferdyblog/tags/:slug/"
  fbcategories = "/ferdyblog/categories/:slug/"
  fb2011 = "/ferdyblog/2011/:slug/"

[taxonomies]
  btag = "btags"
  bcategory = "bcategories"
  b2011 = "b2011"
  b2010 = "b2010"
  b2009 = "b2009"
  b2008 = "b2008"
  b2007 = "b2007"
  b2006 = "b2006"
  fbtag = "fbtags"
  fbcategory = "fbcategories"
  fb2011 = "fb2011"
